const assert = require('node:assert/strict');
const fs = require('node:fs');

const html = fs.readFileSync('static/app.html', 'utf8');
const css = fs.readFileSync('static/app.css', 'utf8');
const foundation = fs.readFileSync('static/css/ui-foundation.css', 'utf8');
const uiFontSize = fs.statSync('static/font/heigo-ui-cn.woff2').size;
const competition = fs.readFileSync('static/js/app.competition.js', 'utf8');
const core = fs.readFileSync('static/js/app.core.js', 'utf8');

assert.match(competition, /function renderDesktopStandingsTable\(/, 'desktop standings should use the compact scoped table');
assert.match(competition, /renderMobileStandingsCards\(level, grouped\[level\]\)/, 'mobile standings cards should always be rendered');
assert.match(competition, /renderDesktopStandingsTable\(level, grouped\[level\]\)/, 'desktop standings table should always be rendered');
assert.doesNotMatch(competition, /mobileMode \? renderMobileStandingsCards/, 'standings rendering must not be locked to the initial viewport');
assert.match(competition, /\['total', '总'\]/);
assert.match(competition, /\['home', '主场'\]/);
assert.match(competition, /\['away', '客场'\]/);
assert.match(competition, /function toggleMobileStandingRow\(level, teamName\)/, 'mobile standings rows should be expandable');
assert.match(competition, /mobile-standings-quick-stats/, 'mobile standings should keep played, goal difference, and points visible in compact mode');
assert.match(competition, /class="mobile-standings-row-toggle"/, 'the whole mobile standings row should toggle details');
assert.doesNotMatch(competition, /class="mobile-standings-expand"/, 'mobile standings should not render a separate expansion button');
assert.match(competition, /expanded \? `<div class="mobile-standings-details"/, 'secondary standings statistics should render only when expanded');

assert.match(html, /class="mobile-more-menu-item mobile-more-utility"[^>]+showJoinHeigoModal/);
assert.match(html, /class="mobile-more-menu-item mobile-more-utility"[^>]+exportData/);
assert.match(html, /class="mobile-more-menu-item mobile-more-utility"[^>]+toggleTheme/);
assert.match(html, /class="mobile-more-menu-label">更多页面</, 'mobile overflow menu should separate secondary pages from utilities');
assert.match(html, /class="mobile-more-menu-label">站点工具</, 'mobile overflow menu should label utility actions');
assert.match(html, /class="nav-tab-icon"[^>]*aria-hidden="true"><svg/, 'primary navigation should use stable SVG icons');
assert.match(html, /class="nav-tab-icon nav-stat-icon"[^>]*aria-hidden="true"><svg/, 'data navigation should use the same SVG language as other primary tabs');
assert.doesNotMatch(html, /class="(?:nav-stat-icon|mobile-bottom-nav-icon mobile-stat-icon)"[^>]*><i>/, 'data navigation should not construct icons from CSS bars');
assert.match(html, /class="database-subtabs competition-primary-tabs surface-card"/, 'competition sections should keep a clear primary switcher');
assert.match(html, /id="competitionSubtabStandings"[^>]*aria-controls="competitionStandingsView"/, 'competition tabs should expose their controlled panels');
assert.match(html, /id="competitionSelectorViewport"[^>]*tabindex="0"/, 'the mobile competition selector should be keyboard scrollable');
assert.match(html, /class="competition-level-group-label">三级联赛</, 'league competitions should be explicitly grouped');
assert.match(html, /class="competition-level-group-label">杯赛</, 'cup competitions should be explicitly grouped');
assert.doesNotMatch(html.slice(0, html.indexOf('<div id="home"')), /⌂|⌕|⇩|◉|⋯/, 'global navigation should not depend on platform glyph icons');
assert.doesNotMatch(fs.readFileSync('static/app.js', 'utf8'), /global-coach-login-mark[^\n]*>◉</, 'the coach login entry should use the shared SVG icon language');

assert.doesNotMatch(css, /transition:\s*all/, 'UI transitions should name exact properties');
assert.match(css, /body:not\(\[data-active-tab="home"\]\) \.shell-topbar/, 'function pages should use the compact shell');
assert.match(css, /\.mobile-standings-list\s*\{\s*display:\s*none/);
assert.match(css, /@media \(max-width: 780px\)[\s\S]*\.mobile-standings-list\s*\{\s*display:\s*grid/);
assert.match(css, /button:not\(:disabled\):active[\s\S]*transform:\s*scale\(0\.98\)/, 'pressable controls should have tactile feedback');
assert.match(css, /scroll-padding-bottom:\s*calc\(var\(--mobile-bottom-nav-height\)/, 'mobile pages should reserve navigation space');
assert.match(css, /Phase 3 navigation and competition hierarchy/, 'Phase 3 navigation rules should stay in one final cascade');
assert.match(css, /Phase 4 unified competition data experience/, 'Phase 4 competition rules should stay in one final cascade');
assert.match(css, /\.competition-module-status\s*\{/, 'competition modules should share one contextual status summary');
assert.match(css, /\.competition-selector\.has-overflow:not\(\.is-at-end\)::after/, 'overflowing mobile competition tabs should expose a right-edge fade');
assert.match(css, /#competition \.competition-level-tabs\s*\{[^}]*width:\s*max-content/, 'competition choices should remain horizontally discoverable without truncating labels');
assert.match(css, /max-height:\s*calc\(100dvh/, 'mobile modals should respect the dynamic viewport');
assert.match(css, /--control-height:\s*44px/, 'the shared design foundation should define a 44px control baseline');
assert.match(css, /\.shell-utility-spinner/, 'long-running global actions should use a stable loading indicator');
assert.match(html, /static\/css\/ui-foundation\.css/, 'the shared UI foundation should be loaded after the legacy stylesheet');
assert.match(html, /id="resultModal"[^>]*role="dialog"[^>]*aria-modal="true"[^>]*aria-labelledby="modalTitle"[^>]*aria-hidden="true"/, 'the shared result modal should expose dialog semantics');
assert.match(html, /class="modal-close"[^>]*aria-label="关闭弹窗"[^>]*>[\s\S]*?<svg/, 'the shared result modal close control should be labelled and use an SVG icon');
assert.match(foundation, /@font-face[\s\S]*font-display:\s*swap/, 'the local UI font should avoid invisible text while loading');
assert.match(foundation, /--text-xs:\s*0\.75rem/, 'the typography scale should not define normal UI copy below 12px');
assert.match(foundation, /--control-height:\s*44px/, 'the shared touch baseline should remain 44px');
assert.match(foundation, /prefers-reduced-motion:\s*reduce/, 'the UI foundation should provide a global reduced-motion mode');
assert.match(foundation, /:where\(button, a, input, select, textarea/, 'keyboard focus should be covered by a shared interaction rule');
assert.match(foundation, /\.ui-state-panel/, 'the shared foundation should provide consistent empty and error states');
assert.match(foundation, /\.ui-toast/, 'the shared foundation should provide non-blocking operation feedback');
assert.match(foundation, /\.ui-field-error/, 'the shared foundation should provide field-level validation feedback');
assert.match(foundation, /\.ui-save-state/, 'the shared foundation should provide autosave state feedback');
assert.match(core, /function renderUiState\(/, 'the core UI layer should expose shared state rendering');
assert.match(core, /function showUiToast\(/, 'the core UI layer should expose shared toast feedback');
assert.match(core, /function setUiButtonBusy\(/, 'the core UI layer should expose async button feedback');
assert.match(core, /function setUiFieldError\(/, 'the core UI layer should expose field-level errors');
assert.match(core, /function handleResultModalKeydown\(/, 'the result modal should trap focus and handle keyboard dismissal');
assert.match(competition, /function updateCompetitionSelectorOverflow\(/, 'competition navigation should measure real overflow instead of showing a static hint');
assert.match(competition, /function toggleMobileScheduleMatchDetails\(/, 'mobile schedules should use progressive detail disclosure');
assert.match(competition, /function toggleMobilePlayerRankingRow\(/, 'mobile player rankings should use progressive detail disclosure');
assert.match(competition, /function toggleMobileSuspensionTeam\(/, 'mobile suspension teams should use progressive detail disclosure');
assert.doesNotMatch(competition, /\bgetCupConfig\(/, 'competition status should use the established cup configuration helper');
assert.match(competition, /competitionCupGroup/, 'unsupported cup choices should be hidden as a complete group');
assert.ok(uiFontSize > 0 && uiFontSize < 300 * 1024, 'the self-hosted Chinese UI font should stay below 300 KiB');

console.log('frontend UI coherence checks passed');
