const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = __dirname;
const html = fs.readFileSync(path.join(root, 'static/app.html'), 'utf8');
const competition = fs.readFileSync(path.join(root, 'static/js/app.competition.js'), 'utf8');
const app = fs.readFileSync(path.join(root, 'static/app.js'), 'utf8');

assert.match(html, /id="cupPhaseTabs"/);
assert.match(html, /id="cupGroupStageBoard"/);
assert.doesNotMatch(html, />小组赛阶段</);
const standingsView = html.match(/<div class="list-view active" id="competitionStandingsView">([\s\S]*?)<div class="list-view" id="competitionScheduleView">/)?.[1] || '';
const scheduleView = html.match(/<div class="list-view" id="competitionScheduleView">([\s\S]*?)<div class="list-view" id="competitionPlayerRankingsView">/)?.[1] || '';
assert.doesNotMatch(standingsView, /id="cupGroupStageBoard"/);
assert.match(scheduleView, /id="cupGroupStageBoard"/);

assert.match(competition, /var currentCupPhase = 'knockout'/);
assert.match(competition, /function setCupPhase\(phase\)/);
assert.match(competition, /function renderCupGroupStageBoard\(\)/);
assert.match(competition, /function renderCupGroupStandingsBoard\(\)/);
assert.match(competition, />小组赛积分榜</);
assert.match(competition, /currentCupPhase === 'knockout'/);
assert.match(competition, /groupCount: 5, teamsPerGroup: 6/);
assert.match(competition, /groupCount: 4, teamsPerGroup: 6/);
assert.match(competition, /fetch\('\/api\/cups\/champions_cup\/groups'\)/);
assert.match(competition, /fetch\('\/api\/cups\/league_cup\/groups'\)/);
assert.match(competition, /function updateCupGroupSuggestions\(input, groupNo, slotNo/);
assert.match(competition, /function resolveCupGroupTeamInput\(input\)/);
assert.match(competition, /function saveCupGroup\(groupNo\)/);
assert.match(competition, /var currentCupGroupScheduleView = 'groups'/);
assert.match(competition, /function setCupGroupScheduleView\(view\)/);
assert.match(competition, />小组赛分组</);
assert.match(competition, />小组赛赛况</);
assert.match(competition, /currentCompetitionSubtab === 'schedule' && cupConfig\?\.groupCount/);
assert.match(competition, /杯赛淘汰赛阶段/);
assert.doesNotMatch(competition, /cup-group-schedule-tabs/);
assert.match(competition, /function calculateCupGroupStandings\(group\)/);
assert.match(competition, /home\.points \+= 3/);
assert.match(competition, /home\.points \+= 1/);
assert.match(competition, /function queueCupGroupScoreSave\(matchId, immediate = false\)/);
assert.match(competition, /group-matches\/\$\{numericId\}/);
assert.match(competition, /body: JSON\.stringify\(\{home_score: payload\.homeScore, away_score: payload\.awayScore\}\)/);
assert.match(competition, /等待另一侧比分/);
assert.match(competition, /function refreshCupGroupQualificationDisplays\(\)/);
assert.match(competition, /qualification_label/);
assert.match(competition, /前 3 名 \+ 最佳小组第 4 名/);
assert.match(competition, /每组前 3 名 \+ 冠军杯转入 4 队/);
assert.match(competition, /cup-group-results-layout is-fixtures-only/);
assert.match(competition, /10 轮、30 场主客场双循环赛程/);
assert.match(competition, /const roundNumbers = \[\.\.\.new Set/);
assert.match(competition, /currentCupPhase === 'group'[\s\S]*?renderCupGroupStandingsBoard\(\)/);
assert.match(competition, /method: 'PUT'/);
assert.match(competition, /同一球队在本项杯赛中只能进入一个小组/);
assert.match(competition, /cupConfig && currentCupPhase === 'knockout'/);
assert.match(competition, /\['standings', 'schedule'\]\.includes\(currentCompetitionSubtab\)/);
assert.match(competition, /currentCompetitionSubtab === 'schedule'[\s\S]*?renderScheduleBoard\(\)/);
assert.match(competition, /renderCupGroupStageBoard\(\)/);
assert.doesNotMatch(competition, /分组名单请在“积分榜 → 小组赛阶段”查看/);

assert.match(app, /params\.set\('cupPhase', competition\.cupPhase\)/);
assert.match(app, /currentCupPhase = competitionState\.cupPhase === 'group'/);
assert.match(app, /params\.set\('cupView', competition\.cupView\)/);
assert.match(app, /currentCupGroupScheduleView = competitionState\.cupView === 'results'/);

console.log('cup phase frontend checks passed');
