const fs = require('fs');
const assert = require('assert');

const html = fs.readFileSync('static/app.html', 'utf8');
const admin = fs.readFileSync('static/js/app.admin.js', 'utf8');
const draws = fs.readFileSync('static/js/app.draws.js', 'utf8');
const app = fs.readFileSync('static/app.js', 'utf8');
const css = fs.readFileSync('static/css/pages/draws.css', 'utf8');
const competition = fs.readFileSync('static/js/app.competition.js', 'utf8');

assert.match(html, /id="drawsTab"[^>]+data-tab="draws"/, 'draws must be a top-level desktop tab');
assert.match(html, /id="mobileDrawsTab"[^>]+data-mobile-tab="draws"/, 'draws must be available from the permitted mobile navigation');
assert.match(html, /id="draws" class="tab-content"/, 'draws must use a top-level page');
assert.doesNotMatch(html, /data-workspace-capability="draws\.write"/, 'draws must no longer be nested in the workspace navigation');
assert.match(html, /data-workspace-capability="archives\.write"/, 'season archives must use their own workspace permission');
assert.match(html, /id="workspaceArchivesView"/, 'season archive workspace view must exist');
assert.match(admin, /can_manage_draws: Boolean\(document\.getElementById\('workspaceEditDraws'\)/, 'account editor must persist draw permission');
assert.match(admin, /can_manage_archives: Boolean\(document\.getElementById\('workspaceEditArchives'\)/, 'account editor must persist archive permission separately');
assert.match(admin, /normalized === 'archives'/, 'workspace navigation must load the archive workbench');
assert.match(app, /draws: \['\/static\/js\/app\.admin\.js', '\/static\/js\/app\.draws\.js'\]/, 'draw frontend module must be loaded for the top-level tab');
assert.match(app, /APP_TAB_NAMES = new Set\(\[[^\]]*'draws'/, 'draws must be registered as a primary app tab');
assert.match(app, /capabilities\?\.includes\('draws\.write'\)/, 'draw tab visibility must follow the independent permission');
assert.match(app, /resolveAccessibleAppTab\(requestedTab\)/, 'direct draw URLs must be denied without the permission');
assert.match(draws, /\/api\/admin\/draws\/proposals\//, 'draw workbench must support rule-based proposals');
assert.match(draws, /\/lottery-pool/, 'draw workbench must expose lottery pool filtering');
assert.match(draws, /\/write-to-cup/, 'draw workbench must expose guarded cup write-through');
assert.match(draws, /export\.xlsx/, 'draw workbench must expose Excel export');
assert.match(draws, /createDrawCandidateList/, 'lottery must link to candidate list draft generation');
assert.match(draws, /custom_team: '自由抽签 · 球队'/, 'draw workbench must support custom team draws');
assert.match(draws, /custom_player: '自由抽签 · 球员'/, 'draw workbench must support custom player draws');
assert.match(draws, /function toggleDrawRoll\(/, 'draw workbench must expose an interruptible rolling stage');
assert.match(draws, /确定当前一签/, 'rolling stage must commit only one result when paused');
assert.match(draws, /function drawLiveProgress\(/, 'rolling stage must expose per-pick progress');
assert.match(draws, /确定当前一签/, 'rolling stage must confirm only one visible draw at a time');
assert.match(draws, /draw\.result\?\.pending_pair/, 'pair draws must preserve a revealed first side while waiting for its opponent');
assert.match(draws, /workspaceDrawRolling = \['locked', 'drawing'\]\.includes\(data\.status\)/, 'remaining candidates must resume rolling after one result is committed');
assert.doesNotMatch(draws, /const endpoint = workspaceCurrentDraw\.draw_type === 'lottery' \? 'next' : 'execute'/, 'non-lottery rolling must no longer execute the entire draw');
assert.match(draws, /`\/api\/admin\/draws\/\$\{workspaceCurrentDraw\.id\}\/next`/, 'every rolling draw must use the single-pick endpoint');
assert.match(draws, /workspaceDrawRollCurrentEntryId = entry\?\.id/, 'the rolling stage must retain the exact candidate visible in the current frame');
assert.match(draws, /JSON\.stringify\(\{entry_id: selectedEntryId\}\)/, 'the click must submit the exact visible candidate to the server');
assert.match(draws, /window\.crypto\?\.getRandomValues/, 'rolling frames should use browser randomness instead of a precomputed server order');
assert.match(draws, /draw\?\.draw_type !== 'lottery'/, 'lottery rolling must use its weighted frame selection branch');
assert.match(draws, /Number\(entry\.weight \|\| 1\)/, 'lottery weight must control how often a player appears while flashing');
assert.match(draws, /任务校验码/, 'the former seed must be described as an audit code rather than the result source');
assert.match(draws, /const config = \{mode\}/, 'custom draws must persist list, group, or pair mode');
assert.match(draws, /entries: \[\]/, 'new draw tasks must start as editable empty drafts');
assert.match(draws, /创建并进入编辑台/, 'new task flow must hand off directly to the draft workbench');
assert.match(draws, /function appendDrawDraftEntries\(/, 'draft workbench must support incremental candidate additions');
assert.match(draws, /function removeDrawPoolEntry\(/, 'draft workbench must support removing individual candidates');
assert.match(draws, /method: 'DELETE'/, 'draw tasks must expose deletion from the workbench');
assert.match(draws, /showConfirmDialog\(\{title: '删除抽签任务'/, 'draw deletion must use the site confirm dialog');
assert.match(draws, /function saveDrawDraftSettings\(/, 'draft settings must remain editable after creation');
assert.match(css, /\.draw-draft-workbench/, 'draft workbench must have a responsive visual layout');
assert.match(css, /\.draw-live-machine/, 'draw workbench must style the live rolling stage');
assert.match(css, /prefers-reduced-motion:reduce/, 'rolling stage must respect reduced motion');
assert.match(css, /@media\(max-width:800px\)/, 'draw workbench must include mobile layout');
assert.match(html, /competitionSubtabArchives/, 'public data statistics must expose season archives');
assert.match(competition, /\/api\/season-archives/, 'public season archive view must use published archive API');

console.log('frontend draw checks passed');
