const assert = require('node:assert/strict');
const fs = require('node:fs');

const html = fs.readFileSync('static/app.html', 'utf8');
const css = fs.readFileSync('static/app.css', 'utf8');
const foundation = fs.readFileSync('static/css/ui-foundation.css', 'utf8');
const shellCss = fs.readFileSync('static/css/shell.css', 'utf8');
const databaseCss = fs.readFileSync('static/css/pages/database.css', 'utf8');
const competitionCss = fs.readFileSync('static/css/pages/competition.css', 'utf8');
const responsiveCss = fs.readFileSync('static/css/responsive.css', 'utf8');
const uiFontSize = fs.statSync('static/font/heigo-ui-cn.woff2').size;
const competition = fs.readFileSync('static/js/app.competition.js', 'utf8');
const databaseSearch = fs.readFileSync('static/js/database.search.js', 'utf8');
const databaseApp = fs.readFileSync('static/js/app.database.js', 'utf8');
const core = fs.readFileSync('static/js/app.core.js', 'utf8');
const app = fs.readFileSync('static/app.js', 'utf8');

assert.match(competition, /function renderDesktopStandingsTable\(/, 'desktop standings should use the compact scoped table');
assert.match(competition, /renderMobileStandingsCards\(level, grouped\[level\]\)/, 'mobile standings cards should always be rendered');
assert.match(competition, /renderDesktopStandingsTable\(level, grouped\[level\]\)/, 'desktop standings table should always be rendered');
assert.doesNotMatch(competition, /mobileMode \? renderMobileStandingsCards/, 'standings rendering must not be locked to the initial viewport');
assert.match(competition, /\['total', '总'\]/);
assert.match(competition, /\['home', '主场'\]/);
assert.match(competition, /\['away', '客场'\]/);
assert.match(competition, /function toggleMobileStandingRow\(level, teamName\)/, 'mobile standings rows should be expandable');
assert.match(competition, /mobile-standings-quick-stats/, 'mobile standings should keep played, goal difference, and points visible in compact mode');
assert.match(competition, /class="mobile-standings-row-toggle"/, 'the whole mobile standings row should toggle details');
assert.doesNotMatch(competition, /class="mobile-standings-expand"/, 'mobile standings should not render a separate expansion button');
assert.match(competition, /expanded \? `<div class="mobile-standings-details"/, 'secondary standings statistics should render only when expanded');

assert.match(html, /class="mobile-more-menu-item mobile-more-utility"[^>]+showJoinHeigoModal/);
assert.match(html, /class="mobile-more-menu-item mobile-more-utility"[^>]+exportData/);
assert.match(html, /class="mobile-more-menu-item mobile-more-utility"[^>]+toggleTheme/);
assert.match(html, /class="mobile-more-menu-label">更多页面</, 'mobile overflow menu should separate secondary pages from utilities');
assert.match(html, /class="mobile-more-menu-label">站点工具</, 'mobile overflow menu should label utility actions');
assert.match(html, /class="nav-tab-icon"[^>]*aria-hidden="true"><svg/, 'primary navigation should use stable SVG icons');
assert.match(html, /class="nav-tab-icon nav-stat-icon"[^>]*aria-hidden="true"><svg/, 'data navigation should use the same SVG language as other primary tabs');
assert.doesNotMatch(html, /class="(?:nav-stat-icon|mobile-bottom-nav-icon mobile-stat-icon)"[^>]*><i>/, 'data navigation should not construct icons from CSS bars');
assert.match(html, /class="database-subtabs competition-primary-tabs surface-card"/, 'competition sections should keep a clear primary switcher');
assert(html.includes('database-module-hero database-search-hero'), 'player search should use the shared database module hero');
assert(html.includes('database-module-hero database-reaction-hero'), 'reaction leaderboard should use the shared database module hero');
assert(html.includes('power-ranking-hero database-module-hero'), 'power ranking should use the shared database module hero');
assert(databaseCss.includes('.database-module-marks'), 'database module heading details should belong to the database stylesheet');
assert(databaseCss.includes('.mobile-reaction-ranking'), 'reaction leaderboard should provide a mobile card view');
assert(databaseSearch.includes("head.classList.remove('is-public-search-style')"), 'public candidate lists should keep the shared module hero visible');
assert(databaseSearch.includes('candidate-public-search-section database-filter-card surface-card'), 'candidate list filters should use the shared database filter card');
assert(databaseApp.includes("activeButton.scrollIntoView({behavior: 'smooth', block: 'nearest', inline: 'center'})"), 'mobile database tabs should reveal the active module');
assert.match(html, /id="competitionSubtabStandings"[^>]*aria-controls="competitionStandingsView"/, 'competition tabs should expose their controlled panels');
assert.match(html, /id="competitionSelectorViewport"[^>]*tabindex="0"/, 'the mobile competition selector should be keyboard scrollable');
assert.match(html, /class="competition-level-group-label">三级联赛</, 'league competitions should be explicitly grouped');
assert.match(html, /class="competition-level-group-label">杯赛</, 'cup competitions should be explicitly grouped');
assert.doesNotMatch(html.slice(0, html.indexOf('<div id="home"')), /⌂|⌕|⇩|◉|⋯/, 'global navigation should not depend on platform glyph icons');
assert.doesNotMatch(fs.readFileSync('static/app.js', 'utf8'), /global-coach-login-mark[^\n]*>◉</, 'the coach login entry should use the shared SVG icon language');

assert.doesNotMatch(css, /transition:\s*all/, 'UI transitions should name exact properties');
assert.match(shellCss, /body:not\(\[data-active-tab="home"\]\) \.header-logo\s*\{[^}]*width:\s*74px[^}]*height:\s*74px/s, 'desktop function pages should retain the full HEIGO logo size');
assert.match(databaseCss, /\.database-module-hero\s*\{[^}]*min-height:\s*86px/s, 'database module headers should not behave like large hero panels');
assert.match(competitionCss, /\.match-event-own-goal-note/, 'competition-only match event styles should live in the competition layer');
assert.match(responsiveCss, /@media \(max-width: 780px\)/, 'migrated mobile overrides should live in the responsive layer');
assert.match(competitionCss, /\.mobile-standings-list\s*\{\s*display:\s*none/);
assert.match(responsiveCss, /@media \(max-width: 780px\)[\s\S]*\.mobile-standings-list\s*\{\s*display:\s*grid/);
assert.match(css, /button:not\(:disabled\):active[\s\S]*transform:\s*scale\(0\.98\)/, 'pressable controls should have tactile feedback');
assert.match(responsiveCss, /scroll-padding-bottom:\s*calc\(var\(--mobile-bottom-nav-height\)/, 'mobile shell ownership should reserve navigation space');
assert.match(competitionCss, /\.competition-module-status\s*\{/, 'competition modules should share one contextual status summary');
assert.match(responsiveCss, /\.competition-selector\.has-overflow:not\(\.is-at-end\)::after/, 'overflowing mobile competition tabs should expose a right-edge fade');
assert.match(responsiveCss, /#competition \.competition-level-tabs\s*\{[^}]*width:\s*max-content/, 'competition choices should remain horizontally discoverable without truncating labels');
assert.match(responsiveCss, /max-height:\s*calc\(100dvh/, 'mobile competition modals should respect the dynamic viewport');
assert.match(css, /--control-height:\s*44px/, 'the shared design foundation should define a 44px control baseline');
assert.match(shellCss, /\.shell-utility-spinner/, 'long-running global actions should belong to the shell layer');
assert.match(html, /static\/css\/ui-foundation\.css/, 'the shared UI foundation should be loaded after the legacy stylesheet');
assert.match(html, /static\/css\/shell\.css/, 'the shell ownership layer should be loaded explicitly');
assert.match(html, /static\/css\/pages\/database\.css/, 'the database page layer should be loaded explicitly');
assert.match(html, /static\/css\/pages\/competition\.css/, 'the competition page layer should be loaded explicitly');
assert.match(html, /static\/css\/responsive\.css/, 'the final responsive layer should be loaded explicitly');
assert.match(html, /id="resultModal"[^>]*role="dialog"[^>]*aria-modal="true"[^>]*aria-labelledby="modalTitle"[^>]*aria-hidden="true"/, 'the shared result modal should expose dialog semantics');
assert.match(html, /class="modal-close"[^>]*aria-label="关闭弹窗"[^>]*>[\s\S]*?<svg/, 'the shared result modal close control should be labelled and use an SVG icon');
assert.match(foundation, /@font-face[\s\S]*font-display:\s*swap/, 'the local UI font should avoid invisible text while loading');
assert.match(foundation, /@font-face\s*\{[\s\S]*?font-weight:\s*400\s*;/, 'the regular font file must not impersonate unavailable bold weights');
assert.doesNotMatch(foundation, /font-weight:\s*400\s+900/, 'bold UI text should use browser weight synthesis instead of the regular glyphs');
assert.match(foundation, /font-synthesis:\s*weight/, 'the UI should synthesize visibly distinct bold weights from the regular local font');
assert.match(foundation, /-webkit-font-smoothing:\s*auto/, 'the UI should preserve native stem contrast instead of forcing thin antialiasing');
assert.match(css, /--text-primary:\s*#203142/, 'light theme primary text should retain strong contrast');
assert.match(css, /--text-secondary:\s*#46586a/, 'light theme secondary text should remain readable on pale surfaces');
assert.match(css, /--text-secondary:\s*#a8b3cf/, 'dark theme secondary text should remain readable on dark surfaces');
assert.ok(css.lastIndexOf('--text-primary: #34364a') > css.lastIndexOf('--text-primary: #203142'), 'the final light-theme cascade should keep primary text dark');
assert.ok(css.lastIndexOf('--text-secondary: #55586d') > css.lastIndexOf('--text-secondary: #46586a'), 'the final light-theme cascade should keep secondary text dark enough');
assert.ok(css.lastIndexOf('--text-primary: #d7defe') > 0, 'the final dark-theme cascade should keep primary text bright');
assert.ok(css.lastIndexOf('--text-secondary: #b6c0e6') > css.lastIndexOf('--text-secondary: #a8b3cf'), 'the final dark-theme cascade should keep secondary text bright enough');
assert.match(foundation, /--text-xs:\s*0\.75rem/, 'the typography scale should not define normal UI copy below 12px');
assert.match(foundation, /--control-height:\s*44px/, 'the shared touch baseline should remain 44px');
assert.match(foundation, /prefers-reduced-motion:\s*reduce/, 'the UI foundation should provide a global reduced-motion mode');
assert.match(foundation, /:where\(button, a, input, select, textarea/, 'keyboard focus should be covered by a shared interaction rule');
assert.match(foundation, /\.ui-state-panel/, 'the shared foundation should provide consistent empty and error states');
assert.match(foundation, /\.ui-toast/, 'the shared foundation should provide non-blocking operation feedback');
assert.match(foundation, /\.ui-field-error/, 'the shared foundation should provide field-level validation feedback');
assert.match(foundation, /\.ui-save-state/, 'the shared foundation should provide autosave state feedback');
assert.match(core, /function renderUiState\(/, 'the core UI layer should expose shared state rendering');
assert.match(core, /function showUiToast\(/, 'the core UI layer should expose shared toast feedback');
assert.match(core, /function setUiButtonBusy\(/, 'the core UI layer should expose async button feedback');
assert.match(core, /function setUiFieldError\(/, 'the core UI layer should expose field-level errors');
assert.match(core, /function handleResultModalKeydown\(/, 'the result modal should trap focus and handle keyboard dismissal');
assert.match(competition, /function updateCompetitionSelectorOverflow\(/, 'competition navigation should measure real overflow instead of showing a static hint');
assert.match(competition, /function toggleMobileScheduleMatchDetails\(/, 'mobile schedules should use progressive detail disclosure');
assert.match(competition, /function toggleMobilePlayerRankingRow\(/, 'mobile player rankings should use progressive detail disclosure');
assert.match(competition, /function toggleMobileSuspensionTeam\(/, 'mobile suspension teams should use progressive detail disclosure');
assert.match(competition, /var currentSuspensionViewFilter = 'active'/, 'suspensions should default to the compact active-record view');
assert.match(competition, /function setSuspensionViewFilter\(filter\)/, 'suspensions should support active, attention, and all-team filters');
assert.match(competition, /function createSuspensionCapturePanel\(level\)/, 'suspension screenshots should use a dedicated read-only capture panel');
assert.match(competition, /kind === 'suspensions' \? createSuspensionCapturePanel\(level\) : null/, 'suspension screenshots should not capture the live editing DOM');
assert.match(competition, /suspension-editor capture-exclude/, 'active suspension editors must be excluded from generic captures');
assert.match(competition, /function queueSuspensionProgressSave\(scope, identifier, immediate = false\)/, 'suspension progress should use debounced autosave');
assert.match(competition, /function saveSuspensionProgress\(scope, identifier, requestedVersion = null\)/, 'suspension progress autosave should have a dedicated persistence path');
assert.match(competition, /suspensionProgressSaveVersions/, 'suspension progress autosave should protect newer edits from stale responses');
assert.match(competition, /网络波动，正在重试/, 'suspension progress should retry once after a transient network interruption');
assert.match(competition, /Suspension progress saved but status refresh failed/, 'a post-save render failure must not be reported as a network save failure');
assert.match(competition, /if \(nextVersion > version\) \{[\s\S]*?clearTimeout\(pendingTimer\)[\s\S]*?suspensionProgressSaveTimers\.delete\(key\)[\s\S]*?saveSuspensionProgress\(scope, identifier, nextVersion\)/, 'suspension progress should clear the pending debounce before flushing edits queued during an in-flight save');
assert.doesNotMatch(competition, />保存进度<\/button>/, 'suspension progress should not expose duplicate manual save buttons');
assert.match(competition, />保存记录<\/button>/, 'the remaining explicit action should clearly save the player record');
assert.match(competitionCss, /\.suspension-capture-grid\s*\{[\s\S]*?grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/, 'suspension capture should use a compact three-column report layout');
assert.match(competitionCss + responsiveCss, /\.suspension-view-filters/, 'suspension view filters should have dedicated responsive styling');
assert.match(app, /competition:\s*\[[^\]]*\/static\/vendor\/html-to-image\.js/, 'competition must load the screenshot dependency directly');
assert.doesNotMatch(competition, /\bgetCupConfig\(/, 'competition status should use the established cup configuration helper');
assert.match(competition, /competitionCupGroup/, 'unsupported cup choices should be hidden as a complete group');
assert.ok(uiFontSize > 0 && uiFontSize < 300 * 1024, 'the self-hosted Chinese UI font should stay below 300 KiB');

console.log('frontend UI coherence checks passed');
