const assert = require('node:assert/strict');
const fs = require('node:fs');

const html = fs.readFileSync('static/app.html', 'utf8');
const css = fs.readFileSync('static/app.css', 'utf8');
const foundation = fs.readFileSync('static/css/ui-foundation.css', 'utf8');
const shellCss = fs.readFileSync('static/css/shell.css', 'utf8');
const databaseCss = fs.readFileSync('static/css/pages/database.css', 'utf8');
const competitionCss = fs.readFileSync('static/css/pages/competition.css', 'utf8');
const responsiveCss = fs.readFileSync('static/css/responsive.css', 'utf8');
const uiFontSize = fs.statSync('static/font/heigo-ui-cn.woff2').size;
const competition = fs.readFileSync('static/js/app.competition.js', 'utf8');
const coaches = fs.readFileSync('static/js/app.coaches.js', 'utf8');
const databaseSearch = fs.readFileSync('static/js/database.search.js', 'utf8');
const databaseApp = fs.readFileSync('static/js/app.database.js', 'utf8');
const core = fs.readFileSync('static/js/app.core.js', 'utf8');
const app = fs.readFileSync('static/app.js', 'utf8');
const home = fs.readFileSync('static/js/app.home.js', 'utf8');

assert.match(competition, /function renderDesktopStandingsTable\(/, 'desktop standings should use the compact scoped table');
assert.match(competition, /renderMobileStandingsCards\(level, grouped\[level\]\)/, 'mobile standings cards should always be rendered');
assert.match(competition, /renderDesktopStandingsTable\(level, grouped\[level\]\)/, 'desktop standings table should always be rendered');
assert.doesNotMatch(competition, /mobileMode \? renderMobileStandingsCards/, 'standings rendering must not be locked to the initial viewport');
assert.match(competition, /\['total', '总'\]/);
assert.match(competition, /\['home', '主场'\]/);
assert.match(competition, /\['away', '客场'\]/);
assert.match(competition, /function toggleMobileStandingRow\(level, teamName\)/, 'mobile standings rows should be expandable');
assert.match(competition, /mobile-standings-quick-stats/, 'mobile standings should keep played, goal difference, and points visible in compact mode');
assert.match(competition, /class="mobile-standings-row-toggle"/, 'the whole mobile standings row should toggle details');
assert.doesNotMatch(competition, /class="mobile-standings-expand"/, 'mobile standings should not render a separate expansion button');
assert.match(competition, /expanded \? `<div class="mobile-standings-details"/, 'secondary standings statistics should render only when expanded');

assert.match(html, /class="mobile-more-menu-item mobile-more-utility"[^>]+showJoinHeigoModal/);
assert.match(html, /class="mobile-more-menu-item mobile-more-utility"[^>]+exportData/);
assert.match(html, /class="mobile-more-menu-item mobile-more-utility"[^>]+toggleTheme/);
assert.match(html, /class="mobile-more-menu-label">更多页面</, 'mobile overflow menu should separate secondary pages from utilities');
assert.match(html, /class="mobile-more-menu-label">站点工具</, 'mobile overflow menu should label utility actions');
assert.match(html, /class="nav-tab-icon"[^>]*aria-hidden="true"><svg/, 'primary navigation should use stable SVG icons');
assert.match(html, /class="skip-link" href="#mainContent"/, 'keyboard users should be able to skip repeated navigation');
assert.match(html, /id="mainContent" class="app-main-content" tabindex="-1"/, 'the skip target should accept programmatic focus');
assert.match(html, /class="nav-tab-icon nav-stat-icon"[^>]*aria-hidden="true"><svg/, 'data navigation should use the same SVG language as other primary tabs');
assert.doesNotMatch(html, /class="(?:nav-stat-icon|mobile-bottom-nav-icon mobile-stat-icon)"[^>]*><i>/, 'data navigation should not construct icons from CSS bars');
assert.match(html, /class="database-subtabs competition-primary-tabs surface-card"/, 'competition sections should keep a clear primary switcher');
assert(html.includes('database-module-hero database-search-hero'), 'player search should use the shared database module hero');
assert(html.includes('database-module-hero database-reaction-hero'), 'reaction leaderboard should use the shared database module hero');
assert(html.includes('power-ranking-hero database-module-hero'), 'power ranking should use the shared database module hero');
assert(databaseCss.includes('.database-module-marks'), 'database module heading details should belong to the database stylesheet');
assert(databaseCss.includes('.mobile-reaction-ranking'), 'reaction leaderboard should provide a mobile card view');
assert(databaseSearch.includes("head.classList.remove('is-public-search-style')"), 'public candidate lists should keep the shared module hero visible');
assert(databaseSearch.includes('candidate-public-search-section database-filter-card surface-card'), 'candidate list filters should use the shared database filter card');
assert(databaseApp.includes("activeButton.scrollIntoView({behavior: 'smooth', block: 'nearest', inline: 'center'})"), 'mobile database tabs should reveal the active module');
assert.match(html, /id="competitionSubtabStandings"[^>]*aria-controls="competitionStandingsView"/, 'competition tabs should expose their controlled panels');
assert.match(html, /id="competitionSelectorViewport"[^>]*tabindex="0"/, 'the mobile competition selector should be keyboard scrollable');
assert.match(html, /class="competition-level-group-label">三级联赛</, 'league competitions should be explicitly grouped');
assert.match(html, /class="competition-level-group-label">杯赛</, 'cup competitions should be explicitly grouped');
assert.doesNotMatch(html.slice(0, html.indexOf('<div id="home"')), /⌂|⌕|⇩|◉|⋯/, 'global navigation should not depend on platform glyph icons');
assert.doesNotMatch(fs.readFileSync('static/app.js', 'utf8'), /global-coach-login-mark[^\n]*>◉</, 'the coach login entry should use the shared SVG icon language');
assert.match(app, /function handleTablistKeyboard\(event\)/, 'tablists should support arrow, Home, and End keyboard navigation');
assert.match(app, /document\.addEventListener\('keydown', handleTablistKeyboard\)/, 'tablist keyboard navigation should be registered once');
assert.doesNotMatch(app, />⌂<|>◎<|>◇<|>⚙</, 'coach account actions should not depend on platform glyph icons');
assert.match(core, /home:[\s\S]*user:[\s\S]*shield:[\s\S]*settings:/, 'the shared SVG icon helper should cover coach account actions');
assert.match(app, /document\.body\?\.classList\.toggle\('global-coach-menu-open', globalCoachMenuOpen\)/, 'opening the coach menu should promote the shell popover layer');
assert.match(app, /if \(previousTab && previousTab !== normalizedTab\) \{[\s\S]*?closeGlobalCoachMenu\(\)/, 'module navigation should dismiss a stale coach popover before compacting the header');
assert.match(shellCss, /body\.global-coach-menu-open header\.shell-header\s*\{[^}]*z-index:\s*calc\(var\(--z-popover\) \+ 10\)/s, 'an open coach menu should sit above mobile navigation and page floaters');
assert.match(shellCss, /\.global-coach-menu\s*\{[^}]*z-index:\s*var\(--z-popover\)[^}]*max-height:\s*min\(70dvh, 540px\)[^}]*overflow-y:\s*auto/s, 'the coach popover should remain visible and internally scrollable');
assert.match(responsiveCss, /\.global-coach-menu\s*\{[^}]*max-height:\s*calc\(100dvh - 88px - var\(--mobile-safe-bottom\)\)[^}]*overflow-y:\s*auto/s, 'the mobile coach popover should stay inside the usable viewport');
assert.match(responsiveCss, /body:not\(\[data-active-tab="home"\]\) \.shell-topbar\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) 44px/s, 'compact mobile pages should place the brand and avatar in one header row');
assert.match(responsiveCss, /body:not\(\[data-active-tab="home"\]\) \.shell-actions\s*\{[^}]*grid-column:\s*2[^}]*width:\s*44px/s, 'the compact mobile account should occupy only the title-side avatar slot');
assert.match(responsiveCss, /body:not\(\[data-active-tab="home"\]\) \.global-coach-copy,[\s\S]*?body:not\(\[data-active-tab="home"\]\) \.global-coach-chevron\s*\{[^}]*display:\s*none !important/s, 'compact mobile pages should hide coach button copy and retain only the avatar');
assert.match(responsiveCss, /body:not\(\[data-active-tab="home"\]\) \.global-coach-menu\s*\{[^}]*right:\s*0[^}]*left:\s*auto/s, 'the compact mobile coach menu should open inward from the viewport right edge');

assert.doesNotMatch(css, /transition:\s*all/, 'UI transitions should name exact properties');
assert.match(shellCss, /body:not\(\[data-active-tab="home"\]\) \.header-logo\s*\{[^}]*width:\s*52px[^}]*height:\s*52px/s, 'desktop function pages should use the compact HEIGO logo size');
assert.match(databaseCss, /\.database-module-hero\s*\{[^}]*min-height:\s*72px/s, 'database module headers should stay compact');
assert.match(competitionCss, /\.match-event-own-goal-note/, 'competition-only match event styles should live in the competition layer');
assert.match(responsiveCss, /@media \(max-width: 780px\)/, 'migrated mobile overrides should live in the responsive layer');
assert.match(competitionCss, /\.mobile-standings-list\s*\{\s*display:\s*none/);
assert.match(responsiveCss, /@media \(max-width: 780px\)[\s\S]*\.mobile-standings-list\s*\{\s*display:\s*grid/);
assert.match(css, /button:not\(:disabled\):active[\s\S]*transform:\s*scale\(0\.98\)/, 'pressable controls should have tactile feedback');
assert.match(responsiveCss, /scroll-padding-bottom:\s*calc\(var\(--mobile-bottom-nav-height\)/, 'mobile shell ownership should reserve navigation space');
assert.match(responsiveCss, /\.horizontal-scroll-hint/, 'overflowing mobile tabs should expose a shared horizontal-scroll hint');
assert.match(competitionCss, /\.competition-module-status\s*\{/, 'competition modules should share one contextual status summary');
assert.match(responsiveCss, /\.competition-selector\.has-overflow:not\(\.is-at-end\)::after/, 'overflowing mobile competition tabs should expose a right-edge fade');
assert.match(responsiveCss, /#competition \.competition-level-tabs\s*\{[^}]*width:\s*max-content/, 'competition choices should remain horizontally discoverable without truncating labels');
assert.match(responsiveCss, /\.competition-selector-viewport\s*\{[^}]*overflow-x:\s*scroll[^}]*touch-action:\s*pan-x pan-y/s, 'the competition selector viewport should be the single native touch scroller');
assert.match(responsiveCss, /#competition \.competition-level-tabs\s*\{[^}]*overflow:\s*visible[^}]*overscroll-behavior:\s*auto/s, 'the competition option rail should not create a nested mobile scroll container');
assert.match(responsiveCss, /\.mobile-schedule-matchup\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) 66px minmax\(0, 1fr\)/s, 'mobile schedule cards should reserve a stable center score lane');
assert.match(responsiveCss, /\.mobile-schedule-team-copy strong\s*\{[^}]*white-space:\s*normal[^}]*-webkit-line-clamp:\s*2/s, 'long mobile schedule team names should wrap to two contained lines');
assert.match(responsiveCss, /\.mobile-schedule-teams strong\s*\{[^}]*overflow:\s*hidden[^}]*-webkit-line-clamp:\s*2/s, 'paired cup fixtures should also contain long team names');
assert.match(responsiveCss, /max-height:\s*calc\(100dvh/, 'mobile competition modals should respect the dynamic viewport');
assert.match(css, /--control-height:\s*44px/, 'the shared design foundation should define a 44px control baseline');
assert.match(shellCss, /\.shell-utility-spinner/, 'long-running global actions should belong to the shell layer');
assert.match(html, /static\/css\/ui-foundation\.css/, 'the shared UI foundation should be loaded after the legacy stylesheet');
assert.match(html, /static\/css\/shell\.css/, 'the shell ownership layer should be loaded explicitly');
assert.doesNotMatch(html, /static\/css\/pages\/(?:database|competition|team)\.css/, 'page-specific styles should not delay the initial shell');
assert.match(app, /const APP_MODULE_STYLES = \{[\s\S]*competition: \['\/static\/css\/pages\/competition\.css'\][\s\S]*database: \['\/static\/css\/pages\/database\.css'\]/, 'page-specific styles should load with their modules');
assert.match(app, /function loadAppStyle\(path\)/, 'the app shell should provide a page-style loader');
assert.match(html, /static\/css\/responsive\.css/, 'the final responsive layer should be loaded explicitly');
assert.match(html, /href="https:\/\/beian\.miit\.gov\.cn\/"[^>]*>京ICP备2026013218号-2<\/a>/, 'the public footer must display the approved ICP filing number');
assert.match(html, /href="https:\/\/beian\.mps\.gov\.cn\/#\/query\/webSearch\?code=11010802049695"[^>]*>[\s\S]*?beian-mps\.png[\s\S]*?京公网安备11010802049695号[\s\S]*?<\/a>/, 'the public footer must display the public security filing icon and approved number in one link');
assert.equal(fs.existsSync('static/images/beian-mps.png'), true, 'the public security filing icon asset must exist');
assert.match(shellCss, /\.footer-compliance\s*\{[^}]*flex-wrap:\s*wrap/s, 'the filing links should wrap safely on narrow screens');
assert.match(shellCss, /\.footer-public-security-link\s*\{[^}]*display:\s*inline-flex[^}]*align-items:\s*center/s, 'the filing icon and text should stay vertically aligned');
assert.match(html, /id="resultModal"[^>]*role="dialog"[^>]*aria-modal="true"[^>]*aria-labelledby="modalTitle"[^>]*aria-hidden="true"/, 'the shared result modal should expose dialog semantics');
assert.match(html, /class="modal-close"[^>]*aria-label="关闭弹窗"[^>]*>[\s\S]*?<svg/, 'the shared result modal close control should be labelled and use an SVG icon');
assert.match(foundation, /@font-face[\s\S]*font-display:\s*swap/, 'the local UI font should avoid invisible text while loading');
assert.match(foundation, /@font-face\s*\{[\s\S]*?font-weight:\s*400\s*;/, 'the regular font file must not impersonate unavailable bold weights');
assert.doesNotMatch(foundation, /font-weight:\s*400\s+900/, 'bold UI text should use browser weight synthesis instead of the regular glyphs');
assert.match(foundation, /font-synthesis:\s*weight/, 'the UI should synthesize visibly distinct bold weights from the regular local font');
assert.match(foundation, /-webkit-font-smoothing:\s*auto/, 'the UI should preserve native stem contrast instead of forcing thin antialiasing');
assert.match(css, /--text-primary:\s*#203142/, 'light theme primary text should retain strong contrast');
assert.match(css, /--text-secondary:\s*#46586a/, 'light theme secondary text should remain readable on pale surfaces');
assert.match(css, /--text-secondary:\s*#a8b3cf/, 'dark theme secondary text should remain readable on dark surfaces');
assert.ok(css.lastIndexOf('--text-primary: #34364a') > css.lastIndexOf('--text-primary: #203142'), 'the final light-theme cascade should keep primary text dark');
assert.ok(css.lastIndexOf('--text-secondary: #55586d') > css.lastIndexOf('--text-secondary: #46586a'), 'the final light-theme cascade should keep secondary text dark enough');
assert.ok(css.lastIndexOf('--text-primary: #d7defe') > 0, 'the final dark-theme cascade should keep primary text bright');
assert.ok(css.lastIndexOf('--text-secondary: #b6c0e6') > css.lastIndexOf('--text-secondary: #a8b3cf'), 'the final dark-theme cascade should keep secondary text bright enough');
assert.match(foundation, /--text-xs:\s*0\.75rem/, 'the typography scale should not define normal UI copy below 12px');
assert.match(foundation, /--control-height:\s*44px/, 'the shared touch baseline should remain 44px');
assert.match(foundation, /prefers-reduced-motion:\s*reduce/, 'the UI foundation should provide a global reduced-motion mode');
assert.match(foundation, /:where\(button, a, input, select, textarea/, 'keyboard focus should be covered by a shared interaction rule');
assert.match(foundation, /\.ui-state-panel/, 'the shared foundation should provide consistent empty and error states');
assert.match(foundation, /\.ui-toast/, 'the shared foundation should provide non-blocking operation feedback');
assert.match(foundation, /\.ui-field-error/, 'the shared foundation should provide field-level validation feedback');
assert.match(foundation, /\.ui-save-state/, 'the shared foundation should provide autosave state feedback');
assert.match(foundation, /\.player-reaction-icon\.is-flower\s*\{[^}]*radial-gradient/s, 'shared UI CSS should always render the flower reaction icon');
assert.match(foundation, /\.player-reaction-icon\.is-egg\s*\{[^}]*linear-gradient/s, 'shared UI CSS should always render the egg reaction icon');
assert.doesNotMatch(databaseCss, /\.player-reaction-icon\.is-(?:flower|egg)/, 'reaction icons should not depend on visiting the lazy-loaded player database');
assert.match(coaches, /class="player-reaction-icon is-flower"/, 'coach profiles should use the shared flower icon component');
assert.match(coaches, /class="player-reaction-icon is-egg"/, 'coach profiles should use the shared egg icon component');
assert.match(core, /function renderUiState\(/, 'the core UI layer should expose shared state rendering');
assert.match(core, /function showUiToast\(/, 'the core UI layer should expose shared toast feedback');
assert.match(core, /function setUiButtonBusy\(/, 'the core UI layer should expose async button feedback');
assert.match(core, /function setUiFieldError\(/, 'the core UI layer should expose field-level errors');
assert.match(core, /function handleResultModalKeydown\(/, 'the result modal should trap focus and handle keyboard dismissal');
assert.match(competition, /function updateCompetitionSelectorOverflow\(/, 'competition navigation should measure real overflow instead of showing a static hint');
assert.match(competition, /function toggleMobileScheduleMatchDetails\(/, 'mobile schedules should use progressive detail disclosure');
assert.match(competition, /function toggleMobilePlayerRankingRow\(/, 'mobile player rankings should use progressive detail disclosure');
assert.match(competition, /class="mobile-player-ranking-row-toggle"[^>]*onclick="toggleMobilePlayerRankingRow/, 'mobile player ranking rows should use the whole compact row as the disclosure control');
assert.doesNotMatch(competition, /class="mobile-player-ranking-toggle"/, 'mobile player rankings should not reserve a separate wide disclosure button');
assert.match(competition, /class="mobile-player-ranking-actions"/, 'expanded mobile player rows should preserve player and team navigation actions');
assert.match(competitionCss, /\.player-ranking-tabs\s*\{[^}]*grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\)/s, 'player ranking metrics should use one shared three-part segmented control');
assert.match(competitionCss, /\.player-ranking-tab\.active\s*\{[^}]*background:\s*color-mix[^}]*color:\s*var\(--accent-primary\)[^}]*transform:\s*none/s, 'player ranking metric selection should match the restrained main-site active style');
assert.match(responsiveCss, /\.player-ranking-tabs\s*\{[^}]*grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\)[^}]*overflow:\s*hidden/s, 'mobile player ranking metrics should remain on one contained row');
assert.match(responsiveCss, /\.player-ranking-tab\s*\{[^}]*min-height:\s*44px[^}]*white-space:\s*nowrap/s, 'mobile player ranking tabs should remain readable touch targets');
assert.match(responsiveCss, /\.mobile-player-ranking-row-toggle\s*\{[^}]*width:\s*100%[^}]*min-height:\s*64px[^}]*grid-template-columns:\s*32px minmax\(0, 1fr\) auto 24px/s, 'the whole mobile player ranking card summary should be a comfortable disclosure target');
assert.match(responsiveCss, /\.mobile-player-ranking-name\s*\{[^}]*grid-column:\s*2[^}]*grid-row:\s*1/s, 'mobile player names should align directly with their ranking number');
assert.match(responsiveCss, /\.mobile-player-ranking-team\s*\{[^}]*grid-column:\s*2[^}]*grid-row:\s*2/s, 'mobile player teams should sit on the lower line beneath the player name');
assert.match(coaches, /coach-auth-action is-workspace[^>]*>进入工作台</, 'coach workspace entry should expose a dedicated account action class');
assert.match(coaches, /coach-auth-action is-logout[^>]*>退出</, 'coach logout should expose a dedicated account action class');
assert.match(html, /class="coach-page-utilities">[\s\S]*?loadCoaches[\s\S]*?syncCoachesFromTeams/, 'coach page utility actions should share a fill-aware wrapper');
assert.match(coaches, /class="coach-auth-summary">[\s\S]*?class="coach-auth-actions">/, 'coach identity information and account actions should render as separate compact rows');
assert.match(responsiveCss, /#coaches \.coach-page-actions\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\)/s, 'mobile coach outer actions should use one full-width column without an empty sibling cell');
assert.match(responsiveCss, /#coaches \.coach-auth-summary\s*\{[^}]*grid-template-columns:\s*repeat\(auto-fit, minmax\(82px, 1fr\)\)/s, 'mobile coach identity pills should share one compact fill-aware row');
assert.match(responsiveCss, /#coaches \.coach-auth-summary > \.coach-auth-pill\s*\{[^}]*min-height:\s*30px[^}]*border-radius:\s*999px[^}]*writing-mode:\s*horizontal-tb[^}]*white-space:\s*nowrap/s, 'mobile coach information pills should stay compact, rounded, and horizontal');
assert.match(responsiveCss, /#coaches \.coach-auth-actions\s*\{[^}]*grid-template-columns:\s*repeat\(auto-fit, minmax\(120px, 1fr\)\)/s, 'mobile coach account actions should evenly fill their row');
assert.match(responsiveCss, /#coaches \.coach-page-utilities\s*\{[^}]*display:\s*flex[^}]*gap:\s*6px/s, 'mobile coach utility actions should share all available width without an empty column');
assert.match(responsiveCss, /#coaches \.coach-page-utilities > \.btn\s*\{[^}]*flex:\s*1 1 0[^}]*border-radius:\s*999px/s, 'visible mobile coach utility buttons should automatically fill the entire panel row');
assert.match(home, /function buildHomeDailyReportPages\(report\)/, 'home daily report should build a dedicated focus page and paginated event pages');
assert.match(home, /filter\(section => section\.title !== '焦点头版'\)/, 'later daily report pages should exclude focus stories already shown on page one');
assert.match(home, /const HOME_DAILY_REPORT_EVENTS_PER_PAGE = 6/, 'daily report event pages should fill the desktop two-column layout with six stories');
assert.match(home, /HOME_DAILY_REPORT_SECTION_DEFINITIONS = \[[\s\S]*label: '超级'[\s\S]*label: '甲级'[\s\S]*label: '乙级'[\s\S]*label: '冠军杯'[\s\S]*label: '联盟杯'[\s\S]*label: '伤停'/, 'non-focus daily report pages should be organized by league, cup, and suspension sections');
assert.match(home, /function classifyHomeDailyReportEntry\(entry\)/, 'daily report events should be classified into their competition section before pagination');
assert.match(home, /function setHomeDailyReportPage\(pageIndex\)/, 'home daily report should expose direct page switching');
assert.match(home, /input type="date"[^>]*max="\$\{escapeHtml\(today\)\}"[^>]*loadHomeDailyReportDate/, 'daily report archive should use a native calendar capped at today');
assert.match(home, /async function loadHomeDailyReportDate\(reportDate\)/, 'daily report archive should fetch the selected historical date without reloading the home page');
assert.match(home, /function shiftHomeDailyReportDate\(dayOffset\)/, 'daily report archive should support adjacent-day navigation');
assert.match(css, /\.home-daily-report-archive\s*\{[^}]*grid-template-columns:\s*minmax\(190px, 1fr\) auto/s, 'daily report archive should integrate date navigation into the reader toolbar');
assert.match(css, /body\.light-mode \.home-daily-report-reader\s*\{[^}]*--report-paper:\s*#fbfcfe/s, 'daily report reader should provide a light paper palette that follows the site theme');
assert.match(css, /\.home-daily-report-reader\s*\{[^}]*--report-paper:\s*#111d2d/s, 'daily report reader should provide a dark newswire palette that follows the site theme');
assert.match(css, /\.home-daily-report-sheet\.is-focus \.home-daily-report-event-grid\s*\{[^}]*grid-template-columns:\s*1fr/s, 'daily report focus page should use a full-width headline flow');
assert.match(competition, /function toggleMobileSuspensionTeam\(/, 'mobile suspension teams should use progressive detail disclosure');
assert.match(competition, /var currentSuspensionViewFilter = 'active'/, 'suspensions should default to the compact active-record view');
assert.match(competition, /function setSuspensionViewFilter\(filter\)/, 'suspensions should support active, attention, and all-team filters');
const suspensionAttentionFilter = competition.slice(competition.indexOf('function suspensionTeamNeedsAttention'), competition.indexOf('function suspensionTeamMatchesFilter'));
assert.doesNotMatch(suspensionAttentionFilter, /suspendedCount/, 'normal suspension records should not be treated as maintenance issues');
assert.match(suspensionAttentionFilter, /team\?\.is_orphaned/, 'orphaned or team-mismatched records should remain in the attention filter');
assert.match(suspensionAttentionFilter, /teamRound === null \|\| teamRound < levelRound/, 'missing or stale team progress should remain in the attention filter');
assert.match(competition, /function createSuspensionCapturePanel\(level\)/, 'suspension screenshots should use a dedicated read-only capture panel');
assert.match(competition, /kind === 'suspensions' \? createSuspensionCapturePanel\(level\) : null/, 'suspension screenshots should not capture the live editing DOM');
assert.match(competition, /suspension-editor capture-exclude/, 'active suspension editors must be excluded from generic captures');
assert.match(competition, /function queueSuspensionProgressSave\(scope, identifier, immediate = false\)/, 'suspension progress should use debounced autosave');
assert.match(competition, /function formatSuspensionRoundProgress\(roundNo, missingLabel = '伤停轮次待补充'\)/, 'suspension round semantics should use one shared formatter');
assert.match(competition, />核对至第<\/span>[\s\S]*?轮 · 适用于下一轮/, 'suspension editors should explain the checked round and the applicable next round in full Chinese');
assert.match(competition, /function saveSuspensionProgress\(scope, identifier, requestedVersion = null\)/, 'suspension progress autosave should have a dedicated persistence path');
assert.match(competition, /suspensionProgressSaveVersions/, 'suspension progress autosave should protect newer edits from stale responses');
assert.match(competition, /网络波动，正在重试/, 'suspension progress should retry once after a transient network interruption');
assert.match(competition, /Suspension progress saved but status refresh failed/, 'a post-save render failure must not be reported as a network save failure');
assert.match(competition, /if \(nextVersion > version\) \{[\s\S]*?clearTimeout\(pendingTimer\)[\s\S]*?suspensionProgressSaveTimers\.delete\(key\)[\s\S]*?saveSuspensionProgress\(scope, identifier, nextVersion\)/, 'suspension progress should clear the pending debounce before flushing edits queued during an in-flight save');
assert.doesNotMatch(competition, />保存进度<\/button>/, 'suspension progress should not expose duplicate manual save buttons');
assert.match(competition, /function queueSuspensionRecordSave\(teamId, immediate = false\)/, 'player suspension records should use debounced autosave');
assert.match(competition, /suspensionRecordSaveVersions/, 'player suspension autosave should protect newer edits from stale responses');
assert.match(competition, /Suspension record autosave interrupted; retrying once/, 'player suspension autosave should retry one transient network failure');
assert.match(competition, /const mergeMode = suspensionRecordEntryModes\.get\(numericTeamId\) !== 'replace'/, 'blank suspension entry should merge repeated player records incrementally');
assert.match(competition, /merge_base_yellow_cards: mergeMode \? mergeBaseYellowCards : null/, 'incremental suspension retries should carry an idempotent base yellow-card count');
assert.match(competition, /suspensionRecordEntryModes\.set\(Number\(teamId\), 'replace'\)/, 'opening an existing record should preserve absolute yellow-card correction');
assert.match(competition, /填写本次新增数量后自动合并/, 'existing suspension records should explain incremental merging before save');
assert.match(competition, /function handleSuspensionTeamCardClick\(event, teamId\)/, 'editable suspension cards should open their editor from the card surface');
assert.match(competition, /const expanded = summary\.hasContent \|\|/, 'teams with suspension records should reveal their details by default');
assert.doesNotMatch(competition, />保存记录<\/button>/, 'player suspension records should not require a separate manual save action');
const suspensionSavePayload = competition.slice(competition.indexOf('async function saveSuspensionPayload'), competition.indexOf('async function saveSuspensionRecord'));
assert.doesNotMatch(suspensionSavePayload, /loadCompetitionData\(\{force: true\}\)/, 'saving one suspension record should not reload and redraw the whole competition page');
assert.match(competitionCss, /\.suspension-capture-grid\s*\{[\s\S]*?grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/, 'suspension capture should use a compact three-column report layout');
assert.match(competitionCss + responsiveCss, /\.suspension-view-filters/, 'suspension view filters should have dedicated responsive styling');
assert.doesNotMatch(app, /competition:\s*\[[^\]]*\/static\/vendor\/html-to-image\.js/, 'competition should not preload the screenshot renderer');
assert.match(app, /function ensureHtmlToImage\(\)/, 'screenshots should load their renderer only when requested');
assert.match(core, /function showConfirmDialog\(options = \{\}\)/, 'destructive actions should use the shared in-app confirmation dialog');
assert.match(core, /function showSuccessToast\(message, options = \{\}\)/, 'routine success feedback should use the shared lightweight toast helper');
assert.match(foundation, /#resultModal \.modal-content[\s\S]*?box-shadow:\s*var\(--shadow-modal\)/, 'shared dialogs should use one modal surface and elevation');
assert.match(foundation, /#resultModal \.modal-close[\s\S]*?width:\s*var\(--control-height\)[\s\S]*?height:\s*var\(--control-height\)/, 'shared dialog close controls should meet the touch target baseline');
assert.match(foundation, /\.ui-toast[\s\S]*?role/, 'toast styling should remain in the shared UI foundation');
assert.doesNotMatch(app + core + competition, /\b(?:alert|confirm)\s*\(/, 'core workflows should not fall back to blocking browser dialogs');
assert.match(app, /const appTabScrollPositions = new Map\(\)/, 'primary modules should preserve their scroll position');
assert.match(app, /expandedLevels:[\s\S]*journeyView:/, 'team-center search and expansion context should be captured in history');
assert.match(app, /suspensionFilter:[\s\S]*expandedStandingRows:[\s\S]*expandedScheduleMatches:[\s\S]*expandedPlayerRankingRows:/, 'competition filters and expanded mobile rows should be captured in history');
assert.match(competition, /function setSuspensionViewFilter\(filter\)[\s\S]*syncAppHistory\('replace'\)/, 'suspension filter changes should replace the current history state');
assert.match(competitionCss, /\.standings-table thead th,[\s\S]*position:\s*sticky/, 'desktop standings and player rankings should keep their headers visible');
assert.match(competitionCss, /\.standings-table th:nth-child\(2\),[\s\S]*position:\s*sticky;[\s\S]*left:\s*0/, 'desktop standings should pin the team column during horizontal scrolling');
assert.match(css, /\.players-list-table th:nth-child\(2\),[\s\S]*position:\s*sticky;[\s\S]*left:\s*0/, 'desktop roster tables should pin the player name column');
assert.match(databaseCss, /#dbPlayersTable > \.db-players-table th:first-child,[\s\S]*position:\s*sticky;[\s\S]*left:\s*0/, 'desktop database results should pin the player name column');
assert.doesNotMatch(competition, /\bgetCupConfig\(/, 'competition status should use the established cup configuration helper');
assert.match(competition, /competitionCupGroup/, 'unsupported cup choices should be hidden as a complete group');
assert.ok(uiFontSize > 0 && uiFontSize < 300 * 1024, 'the self-hosted Chinese UI font should stay below 300 KiB');

console.log('frontend UI coherence checks passed');
