const assert = require('assert');
const fs = require('fs');

const app = fs.readFileSync('static/app.js', 'utf8');
const html = fs.readFileSync('static/app.html', 'utf8');
const css = [
    fs.readFileSync('static/css/pages/team.css', 'utf8'),
    fs.readFileSync('static/css/responsive.css', 'utf8'),
].join('\n');
const shellCss = fs.readFileSync('static/css/shell.css', 'utf8');
const team = fs.readFileSync('static/js/app.team.js', 'utf8');
const players = fs.readFileSync('static/js/app.players.js', 'utf8');
const coaches = fs.readFileSync('static/js/app.coaches.js', 'utf8');

assert(app.includes("team: ['/static/js/app.coaches.js', '/static/vendor/html-to-image.js', '/static/js/app.players.js', '/static/js/app.team.js']"), 'team module assets should include lineup and image export dependencies');
assert(app.includes("'overview', 'team', 'players'"), 'team should be a valid hidden SPA tab');
assert(app.includes("params.set('team', normalized.team.name)"), 'team deep link should be written to the URL');
assert(app.includes("const teamParam = params.get('team')"), 'team deep link should be read from the URL');
assert(app.includes("currentTeamDetailName = '';\n    await showTab('team'"), 'top-level team center entry should reset to the landing page');
assert(app.includes('return openTeamDetail(teamName, options)'), 'legacy team entry should open team detail');
assert(app.includes('async function openTeamRoster(teamName'), 'full roster navigation should remain available');
assert(app.includes("const MOBILE_PRIMARY_TABS = new Set(['home', 'team'"), 'team center should replace roster in mobile primary navigation');

assert(html.includes('id="team" class="tab-content"'), 'team tab shell should exist');
assert(html.includes('id="teamDetailRoot"'), 'team detail root should exist');
assert(html.includes('class="nav-tab-icon team-nav-icon"'), 'team center should use its own jersey navigation icon');
assert(html.includes('class="mobile-bottom-nav-icon team-nav-icon"'), 'mobile team navigation should reuse the jersey icon');

assert(team.includes('/api/players/team/${encoded}'), 'team roster API should be loaded');
assert(team.includes('function renderTeamCenterLanding()'), 'team center landing page should render before a team is selected');
assert(team.includes('id="teamCenterSearchInput"'), 'team center landing should include club and coach search');
assert(team.includes('team-center-coach-access'), 'team center welcome should include a coach login shortcut');
assert(team.includes("showCoachLoginPanel({context: 'team-center'})"), 'team center login should reuse the coach account login modal');
assert(coaches.includes('coachLoginSuccessContext'), 'coach login should preserve the team-center success context');
assert(coaches.includes('onsubmit="event.preventDefault(); coachLogin();"'), 'coach login should support standard form submission and Enter');
assert(team.includes('async function openCoachLinkedTeam('), 'coach login should resolve and open the linked team');
assert(team.includes('Number(team.id) === Number(account.team_id)'), 'linked team navigation should prefer the stable team id');
assert(team.includes('id="teamCenterDirectory"'), 'team center landing should include the 54-team directory');
assert(team.includes('function toggleTeamCenterLeague(level)'), 'mobile team directory should expose collapsible league groups');
assert(team.includes('teamCenterExpandedInitialized'), 'the default league group should only be initialized once so every group can be collapsed');
assert(team.includes('aria-controls="${contentId}"'), 'league group toggles should expose their controlled directory');
assert(team.includes("linkedTeam?.level || '超级'"), 'mobile team directory should prefer the linked team league and otherwise open super league');
assert(team.includes("openTeamDetail(decodeURIComponent('${encodedName}'))"), 'landing team cards should open team detail');
assert(team.includes('/api/attributes/power-ranking?shape=all&limit=all&team=${encoded}'), 'all growth shapes should be loaded for CA estimation');
assert(team.includes('/api/teams/${team.id}/lineup'), 'saved team lineup should be loaded');
assert(team.includes('/api/teams/${team.id}/cup-outlook'), 'team cup outlook should be loaded');
assert(team.includes("fetchJsonOrThrow('/api/teams/power-summaries')"), 'level-wide team power summaries should be loaded');
assert(team.includes('renderRosterFormationPreview({teamName: team.name'), 'team center should render an eleven-player pitch preview');
assert(players.includes('...Object.keys(picks)'), 'saved free-position lineup slots should remain visible in the team preview');
assert(team.includes('function openTeamLineupEditor()'), 'team lineup editor should be available');
assert(team.includes('function teamDetailGroupMatchSeries('), 'consecutive rounds against one opponent should be grouped');
assert(team.includes('upcomingMatches.slice(0, 4)'), 'the merged upcoming fixture panel should show four rounds at once');
assert(team.includes('team-next-series-list'), 'upcoming fixtures should use the grouped future-schedule card style');
assert.strictEqual((team.match(/<h2>赛事征程<\/h2>/g) || []).length, 1, 'team center should render one competition journey panel');
assert(team.includes('function setTeamJourneyView(view)'), 'competition journey should switch between league and cups');
assert(team.includes('剩余 ${teamDetailSafeNumber(item.remaining_opponent_count)} 个对手'), 'cup journey should show remaining distinct opponents');
assert(team.includes('${teamDetailSafeNumber(opponent.played_legs)}</b>/2'), 'cup journey should show two-leg opponent progress');
assert(team.includes('item.qualification_label'), 'cup journey should show the canonical qualification result');
assert(team.includes("item.phase === 'knockout'"), 'specific next fixture details should be limited to the knockout phase');
assert(!team.includes("item.phase === 'group' ? '下一组对阵'"), 'group journey should not render specific next matchup details');
assert(team.includes("currentCupGroupScheduleView = 'results'"), 'cup group journey should open the group results view');
assert(!team.includes('<h2>接下来 4 轮</h2>'), 'the duplicate next-four panel title should be removed');
assert(!team.includes("<h2>下一组对阵</h2>"), 'the old next-pair UI should be removed');
assert(!team.includes(" : 'VS'"), 'unplayed team-center fixtures should not render VS labels');
assert(team.includes('阵型预览'), 'lineup average HEIGO power should be displayed');
assert(team.includes('全队球员'), 'full-roster average HEIGO power should be displayed');
assert(team.includes('teamPowerSummary?.lineup_average'), 'lineup average should use the canonical estimated summary value');
assert(team.includes('teamPowerSummary?.roster_average'), 'roster average should use the canonical estimated summary value');
assert(team.includes('lineup_rank'), 'lineup average should show its current-level rank');
assert(team.includes('roster_rank'), 'roster average should show its current-level rank');
assert(team.includes('function copyTeamRosterImage()'), 'team roster image copy should be available');
assert(team.includes("const TEAM_ROSTER_VIEW_MODES = new Set(['compact', 'detail', 'cards'])"), 'team roster should support compact, detail, and card views');
assert(team.includes("return window.matchMedia?.('(max-width: 700px)').matches ? 'cards' : 'compact'"), 'mobile team roster should default to cards while desktop keeps compact mode');
assert(team.includes('function teamDetailDetailedRoster('), 'team roster should provide a complete field table');
assert(team.includes('function teamDetailRosterCards('), 'team roster should provide player cards');
assert(team.includes('<th>年龄</th><th>初始 CA</th><th>当前 CA</th><th>当前 PA</th><th>位置</th><th>国籍</th><th>工资</th><th>名额</th><th>复制</th>'), 'detail roster should expose all requested roster fields');
assert(team.includes('async function copyTeamRosterPlayer('), 'each team roster player should support copying');
assert(team.includes('async function copyTeamLineupImage()'), 'team center should copy the visible lineup image directly');
assert(team.includes("navigator.clipboard.write([new ClipboardItem({'image/png': blobPromise})])"), 'lineup image should prefer clipboard copy');
assert(team.includes('showTeamLineupImageFallback(blob, fileName)'), 'lineup image should fall back to preview and download');
assert(team.includes('team-panel-actions'), 'lineup copy and edit actions should share one header action group');
assert(!players.includes('onclick="saveRosterFormationImage()">下载阵容图</button>'), 'lineup image action should be removed from the editor toolbar');
assert(team.includes('工资帽 ${teamDetailFormatNumber(wageCap, 2)}M'), 'team wage card should include the current wage cap');
assert(team.includes('teamDetailGrowthStepFromCa'), 'league CA should select an estimated growth shape');
assert(team.includes('Number(match.home_team_id) === Number(team.id)'), 'imported fixtures should match teams by stable id');
assert(team.includes('sorted.map(player =>'), 'team center should render the complete team roster');
assert(team.includes('teamDetailFormatNumber(item.heigo_power, 2)'), 'HEIGO power should use two decimals');
assert(team.includes('<span>加权战力</span>'), 'power core should label weighted power explicitly');
assert(team.includes('<span>HEIGO 战力</span><small>前 '), 'power percentile should be visually bound to HEIGO power');
assert(team.includes('Promise.allSettled'), 'partial API failure should not break the whole page');

assert(css.includes('.team-detail-primary-grid'), 'desktop team layout should exist');
assert.match(css, /\.team-detail-side-stack\s*\{[\s\S]*?display:\s*grid;[\s\S]*?grid-template-rows:\s*auto auto;[\s\S]*?align-content:\s*start;/, 'team journey and discipline cards should keep natural height instead of stretching to the lineup');
assert(shellCss.includes('.team-nav-icon .team-nav-shirt'), 'team center jersey icon should inherit the navigation theme color from the shell layer');
assert.match(css, /\.team-detail-primary-grid,\s*\.team-detail-secondary-grid\s*\{[\s\S]*?display:\s*grid;[\s\S]*?grid-template-columns:\s*minmax\(0, 1\.65fr\) minmax\(290px, \.75fr\);/, 'the four core team modules should share the same column boundary');
assert.match(css, /\.team-match-venue\s*\{[\s\S]*?font-size:\s*\.78rem;/, 'home and away labels should be visually prominent');
assert(css.includes('.team-center-lineup-capture'), 'embedded football pitch styling should exist');
assert(css.includes('.team-match-series-card'), 'two-leg fixture styling should exist');
assert(css.includes('.team-next-series-list'), 'merged upcoming fixture styling should exist');
assert(css.includes('.team-journey-tabs'), 'competition journey tabs should be styled');
assert(css.includes('.team-cup-opponent-row'), 'cup opponent progress should be styled');
assert(css.includes('.team-power-summary-values'), 'the dual HEIGO average card should be styled');
assert(css.includes('.team-power-heigo small'), 'HEIGO percentile should have a dedicated label style');
assert(css.includes('.team-roster-export-card'), 'roster image export styling should exist');
assert(css.includes('.team-roster-view-switch'), 'team roster should have a dedicated three-way view switch');
assert(css.includes('.team-roster-detail-table'), 'team roster detailed table should be styled');
assert(css.includes('.team-roster-card-grid'), 'team roster card grid should be styled');
assert(css.includes('.team-center-club-grid'), 'team center directory grid should exist');
assert(css.includes('.team-center-league-group.is-collapsed .team-center-club-grid'), 'mobile team directory should hide collapsed league groups');
assert(team.includes('return options.compact ? renderLeagueLevelSignature'), 'team center should reuse the shared compact league signature');
assert(team.includes('${renderLeagueTierSet()}'), 'team center welcome should display the three league signatures together');
assert(css.includes('.team-center-coach-access'), 'coach login shortcut should have dedicated responsive styling');
assert.match(css, /\.team-center-coach-access\s*\{[\s\S]*?--team-coach-accent:\s*#25a96f;[\s\S]*?min-width:\s*250px;[\s\S]*?min-height:\s*74px;/, 'coach login shortcut should use the team UI green accent and a larger click target');
assert.match(css, /body:not\(\.light-mode\) \.team-center-coach-access\s*\{\s*--team-coach-accent:\s*#36d6a0;/, 'coach login shortcut should adapt to the dark team-center background');
assert.match(css, /\.team-center-switcher-control select\s*\{[\s\S]*?width:\s*100%;[\s\S]*?min-width:\s*0;[\s\S]*?min-height:\s*52px;/, 'detail team selector should be high contrast and touch friendly');
assert(css.includes('@media (max-width: 700px)'), 'mobile team layout should exist');
assert.match(css, /\.team-detail-toolbar-meta > span:last-child\s*\{\s*display:\s*none;/, 'mobile toolbar should hide only its direct metadata child');
assert.match(css, /\.team-detail-toolbar-meta \.league-level-signature\s*\{[\s\S]*?width:\s*40px;[\s\S]*?height:\s*40px;[\s\S]*?min-height:\s*40px;[\s\S]*?padding:\s*0;[\s\S]*?justify-content:\s*center;/, 'mobile league badge should use a centered square frame');
assert.match(css, /\.team-detail-toolbar-meta \.league-level-copy\s*\{\s*display:\s*none;/, 'mobile league badge should intentionally hide its copy without affecting alignment');
assert(css.includes('@media (prefers-reduced-motion: reduce)'), 'reduced motion should be respected');

console.log('frontend team detail checks passed');
